export const mappingFields = [
    { xml: 'TYPFZGNR', xlsx: 'car.vin' },
    { xml: 'TYPINTNR', xlsx: 'car.external_id' },
    { xml: ['TYPMARBEZ', 'TYPBEZ'], xlsx: 'car.name', type: 'multiple' },
    { xml: '$.TYPLAUFNR', xlsx: 'ChassisNr', hidden: true, type: 'attribute' },
    { xml: 'PICTURES.0.PIC', xlsx: 'Picture', hidden: true, type: 'picture' },

    { xml: 'TYPERSTIV', xlsx: 'InitialRegistration' },
    { xml: 'TYPKMIST', xlsx: 'Milage' },
    { xml: 'TYPPS', xlsx: 'EnginePowerHP' },
    { xml: 'TYPKW', xlsx: 'EnginePowerKW' },
    { xml: 'TYPZYLINDER', xlsx: 'EngineCylinder' },
    { xml: 'TYPHUBRAUM', xlsx: 'EngineCapacity' },
    { xml: 'TYPTXTGETRCD2', xlsx: 'GearType' },
    { xml: 'TYPVERBGES', xlsx: 'ConsumptionLiquidExtraCombined' },
    { xml: 'TYPVERBLAND', xlsx: 'ConsumptionLiquidExtraUrban' },
    { xml: 'TYPVERBSTADT', xlsx: 'ConsumptionLiquidUrban' },
    { xml: 'TYPCO2', xlsx: 'EmissionCo2Liquid' },
    { xml: 'TYPTXTTRBSTCD2', xlsx: 'PrimaryFuelType' },
    { xml: 'TYPTXTEMISCODECD2', xlsx: 'EmissionClass' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingInitialPayment', defaultVal: 0 },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingRate', defaultVal: 0 },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingMonthlyAllInRate' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingSpecialRedemption' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingDuration', defaultVal: 0 },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingEffRateOfInterest' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingResidualValue' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingBankName' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingGrossCreditAmount' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingServiceFee' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingRateInsurance' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingDebitInterestRate' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingDebitInterestType' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingNetCreditAmount' },
    {
        xml: 'EMPTY_NEED_WRITE',
        xlsx: 'LeasingExcessMileageCosts',
        defaultVal: 0,
    },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingTransferCosts' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LeasingOtherConditions' },
    { xml: 'TYPVPB2C', xlsx: 'PublicPriceValue', defaultVal: 0 },
    { xml: 'TYPDAMANP', xlsx: 'ListPriceValue', defaultVal: 0 },
    { xml: 'TYPGARDAUMT', xlsx: 'WarrantyDuration' },
    { xml: 'TYPGARKMMA', xlsx: 'WarrantyMilage' },
    { xml: 'TYPGARTEXT', xlsx: 'WarrantyText' },
    { xml: 'TYPFARBE', xlsx: 'BodyColor' },
    { xml: 'TYPPOLSTER', xlsx: 'Covering' },
    { xml: 'TYPMARBEZ', xlsx: 'Brand' },
    { xml: 'TYPBEZ', xlsx: 'Model' },
    { xml: 'SERIE.0.SAPOS', xlsx: 'StandardEquipment', type: 'array' },
    { xml: 'SONDER.0.SAPOS', xlsx: 'SpecialEquipment', type: 'array' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'AbMFK' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'Fuel' },
    { xml: 'EMPTY_NEED_WRITE', xlsx: 'LastCheck' },
];
