name: xoontec_chat
description: Xoontec chat application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  formz: ^0.2.0
  equatable: ^1.2.3
  # authentication_repository:
  #   path: packages/authentication_repository
  # user_repository:
  #   path: packages/user_repository
  intl: ^0.16.1
  retrofit: ^1.3.4
  shared_preferences: ^0.5.7
  rxdart: ^0.22.6
  dio: ^3.0.10
  json_annotation: ^3.0.0
  json_serializable: ^3.3.0
  provider: ^4.3.2+1
  tuple: ^1.0.3
  encrypt: ^4.0.0
  hex: ^0.1.2

  # signalr
  signalr_core: any

  # web_view
  flutter_webview_plugin: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.0.0
  mockito: ^4.1.1
  retrofit_generator: ^1.3.7+5
  build_runner: ^1.10.1
  build_resolvers: ^1.3.10
  intl_translation: ^0.17.1
flutter:
  uses-material-design: true
