import { AppHeaderComponent } from './app-header';
//import { BreadcrumbComponent } from './breadcrumb';
//import { BreadcrumbItemComponent } from './breadcrumb-item';
import { ControlSidebarComponent } from './control-sidebar';
//import { NotificationBoxComponent } from './notification-box';
import { UserBoxComponent } from './user-box';
import { DialogUserProfileComponent } from './dialog-user-profile';
import { LayoutSettingComponent } from './layout-setting';

//import * as parkedItem from './parked-item';
import { WidgetTemplateSettingComponent } from './widget-template-setting';
import { XnMenuBarComponent } from './xn-menu-bar';
import * as xnTab from './xn-tab';
//import * as xnWorkingModules from './xn-working-modules';
//import { XnMediacodeDialogComponent } from './xn-mediacode-dialog';
import * as xnAdditionalInformation from './xn-additional-information';
import * as xnCentralPageView from './xn-central-page';
import * as widget from './widget';
import * as xnForm from './xn-form';
import * as xnControl from './xn-control';
import * as xnFile from './xn-file';
import * as feedback from './feedback';
//import * as artMedia from './article-media-manager';
import { ImageZoomerComponent } from './image-zoomer';
//import { BusinessCostStatusTabComponent } from './business-cost-status-tab';
import * as property from './property-panel';
//import * as customerHistory from './customer-history';
//import { SendToAdminDialogComponent } from './send-to-admin-dialog';
import * as moduleWelcome from './module-welcome';
import { DialogApplyWidgetSettingsComponent } from './dialog-apply-widget-settings';
import * as translate from './translation';
import { CapturedDocumentDetailComponent } from '@app/pages/private/dms-dashboard/components/captured-document-detail';
import { NotificationPopupComponent } from './notification-popup';
import { FileProcessPopupComponent } from './file-process-popup';
import { BlockUIDialogComponent } from './block-ui';
import { WidgetContextMenuComponent } from './widget-context-menu';

export const WIDGETS_COMPONENTS = [
    AppHeaderComponent,
    //BreadcrumbComponent,
    //BreadcrumbItemComponent,
    ControlSidebarComponent,
    UserBoxComponent,
    DialogUserProfileComponent,
    LayoutSettingComponent,
    //parkedItem.ParkedItemComponent,
    //parkedItem.ParkedItemListComponent,
    //parkedItem.ParkedItemGuideComponent,
    //parkedItem.ParkedItemDropdownComponent,
    //parkedItem.ParkedItemProjectStatusComponent,
    WidgetTemplateSettingComponent,
    XnMenuBarComponent,
    NotificationPopupComponent,
    FileProcessPopupComponent,
    BlockUIDialogComponent,
    xnTab.XnTabComponent,
    xnTab.XnTabButtonComponent,
    xnTab.XnTabContentComponent,
    xnTab.XnTabContentNewMainTabComponent,
    xnTab.XnTabContentNewOtherTabComponent,
    xnTab.XnTabHeaderComponent,
    xnTab.XnTabHeaderSubFormComponent,
    xnTab.XnTabHeaderMenuComponent,
    xnTab.XnTabContentSimpleTabsComponent,
    xnTab.XnVerticalTabComponent,
    xnTab.XnVerticalTabHeaderComponent,
    xnTab.XnVerticalTabContentComponent,
    //xnWorkingModules.XnWorkingModulesComponent,
    //xnWorkingModules.XnWorkingModulesParkedItemsComponent,
    xnAdditionalInformation.XnAdditionalInformationMainComponent,
    xnAdditionalInformation.XnAdditionalInformationPageComponent,
    xnAdditionalInformation.XnAdditionalInformationTabComponent,
    xnAdditionalInformation.XnAdditionalInformationTabPlusComponent,
    xnAdditionalInformation.XnAdditionalInformationTabContentComponent,
    xnCentralPageView.XnTabPageViewComponent,
    xnCentralPageView.XnSinglePageViewComponent,
    xnCentralPageView.XnDoublePageViewComponent,
    xnCentralPageView.XnDoublePageViewHorizontalComponent,
    xnCentralPageView.XnDoublePageViewVerticalComponent,
    widget.WidgetContainerComponent,
    widget.WidgetModuleComponent,
    widget.WidgetTranslateComponent,
    widget.WidgetFormComponent,
    widget.FilterMenuComponent,
    widget.WidgetModuleInfoTranslationComponent,
    widget.EditDropdownComponent,
    widget.WidgetEditDialogComponent,
    widget.WidgetCommunicationDialogComponent,
    widget.WidgetTranslationComponent,
    widget.PaperworkComponent,
    widget.ArrowAnimationComponent,
    widget.XnWidgetMenuStatusComponent,
    widget.WidgetUserEditingListComponent,
    widget.WidgetReloadMessageComponent,
    widget.WidgetSubtitleComponent,
    widget.WidgetArticleTranslationComponent,
    widget.WidgetArticleTranslationDialogComponent,
    widget.WidgetRoleTreeGridComponent,
    widget.WidgetBlankComponent,
    widget.DialogAddWidgetTemplateComponent,
    widget.ArticleTemplateImageUploadComponent,
    widget.ArticleUploadStatusComponent,
    widget.NewLotDialogComponent,
    widget.WidgetProfileSavingComponent,
    widget.WidgetProfileSelectComponent,
    widget.DialogUserRoleComponent,

    widget.DialogDeleteCancelComponent,
    widget.DoubletteGroupComponent,
    widget.WidgetReportComponent,
    widget.WidgetModulesOverviewComponent,
    widget.WidgetDocumentPathComponent,
    widget.WidgetInvoiceInfoComponent,
    widget.WidgetBankInfoComponent,
    widget.WidgetKontaktComponent,
    widget.WidgetContractComponent,
    widget.WidgetClassificationComponent,
    widget.ControlDynamicHandlerComponent,
    widget.WidgetNotesComponent,
    widget.WidgetElasticSearchComponent,
    widget.WidgetDmsActionsComponent,
    widget.WidgetScannerComponent,
    widget.WidgetScanSummaryComponent,
    widget.WidgetMyContactTreeComponent,
    widget.WidgetContactListComponent,
    widget.WidgetAttachmentComponent,
    widget.WidgetMyDmSummaryComponent,
    widget.WidgetMyDmFolderTreeComponent,
    widget.WidgetEsMyDmManagementComponent,
    widget.WidgetSearchMyDmComponent,
    widget.WidgetFileExplorerComponent,
    widget.WidgetCloudManagementComponent,
    widget.WidgetImportUploadFileComponent,
    widget.WidgetHistoryComponent,
    widget.WidgetFavouriteFolderComponent,
    widget.WidgetToggleCapturedFormComponent,
    widget.WidgetScanStructTreeComponent,
    widget.WidgetEmailViewerComponent,
    widget.WidgetEmailAttachmentComponent,
    widget.WidgetNoteFormComponent,
    widget.EmailNoteComponent,
    widget.WidgetPaymentOverviewComponent,
    widget.WidgetInvoiceSupplierInformationComponent,
    widget.WidgetInvoiceMandanOverviewComponent,
    widget.WidgetPayementInformationComponent,
    widget.WidgetInoviceAddonComponent,
    widget.WidgetOwnerDocumentComponent,
    widget.WidgetInvoiceAddonV2Component,
    widget.WidgetIndexingFileComponent,
    widget.WidgetBranchesComponent,
    widget.WidgetUploadBranchesComponent,
    //SendToAdminDialogComponent,
    //XnMediacodeDialogComponent,
    xnFile.FileUploadComponent,
    xnFile.XnFileExplorerComponent,
    xnFile.XnUploadTemplateFileComponent,
    xnFile.ListTemplateOfFileComponent,
    xnFile.XnTableUploadedFilesComponent,
    ImageZoomerComponent,
    //BusinessCostStatusTabComponent,
    property.PropertyPanelComponent,
    property.PropertyPanelGridComponent,
    property.PropertyPanelGridValueComponent,
    property.PropertyPanelGridValueDialogComponent,
    property.PropertyPanelOrderFieldDialogComponent,
    property.PropertyPanelOrderFieldDisplayItemComponent,
    property.PropertyPanelGridFieldDataDialogComponent,
    property.PropertyPanelDateFormatDialogComponent,
    //xnForm.AdContactMainFieldComponent,
    xnForm.ControlMessagesComponent,
    //xnForm.SearchMediaCodeComponent,
    //xnForm.XnFormFgAddressComponent,
    //xnForm.AdministrationFormComponent,
    //xnForm.AdMainFieldComponent,
    //xnForm.AdContactFormComponent,
    //xnForm.CustContactFormComponent,
    //xnForm.CustomerFormComponent,
    xnForm.ControlFocusComponent,
    //xnForm.AdChequesPRNComponent,
    //xnForm.AdCashProviderPRNFormComponent,
    //xnForm.AdCashProviderProviderCostFormComponent,
    //xnForm.PaymentAccountFormComponent,
    //xnForm.ArticleFormComponent,
    //xnForm.ArticleSetCompositionFormComponent,
    //xnForm.ArticlePurchasingFormComponent,
    //xnForm.MediaCodeT2FormComponent,
    //xnForm.CampaignInterReTakesFormComponent,
    //xnForm.CampaignArticleFormComponent,
    //xnForm.CampaignCountryT1FormComponent,
    //xnForm.BusinessCostFormComponent,
    xnForm.FileTreeViewComponent,
    //xnForm.CampaignCountryT1BFormComponent,
    //xnForm.EditCheckBoxComponent,
    //xnForm.BusinessCostHeaderFormComponent,
    //xnForm.BusinessCostRowFormComponent,
    //xnForm.CampaignCombineFormComponent,

    //xnForm.SummaryCommandComponent,
    //xnForm.WidgetManageFormComponent,
    xnForm.DispatcherFromStep1Component,
    xnForm.DispatcherFromStep2Component,
    xnForm.DispatcherFromCombineComponent,
    xnForm.ScanAssignmentStep1Component,
    xnForm.ScanAssignmentStep2Component,
    xnForm.ScanAssignmentStep3Component,
    xnForm.ScanAssignmentMainComponent,
    xnForm.ToolContainerComponent,
    xnForm.SmartWizzardComponent,
    xnForm.DoubletCheckCombineComponent,
    xnForm.DoubletCheckMainComponent,
    xnForm.DoubletCheckArchiveComponent,
    xnForm.ElasticSearchSyncGridComponent,
    xnForm.ElasticSearchSyncMainComponent,
    xnForm.ElasticSearchSyncTabComponent,
    xnForm.ElasticSearchSyncTreeComponent,
    xnForm.ElasticSearchSyncCommandComponent,
    //xnForm.XnFormQuillEditorToolbarComponent,
    //xnForm.ReturnRefundInvoiceComponent,
    //xnForm.ArticleOrdersComponent,
    //xnForm.ArticleSearchDialogComponent,
    //xnForm.ArticleSearchComponent,
    //xnForm.ArticleCampaignSearchComponent,
    //xnForm.RefundPaymentFormComponent,
    //xnForm.EmailSettingPopupComponent,
    //xnForm.ReturnPaymentComponent,
    //xnForm.ReturnRefundInvoiceNumberComponent,
    //xnForm.SortingGoodsEditFormComponent,
    //xnForm.WarehouseMovementSelectArticleComponent,
    //xnForm.WarehouseMovementUpdatingFormComponent,
    //xnForm.StockCorrectionComponent,
    //xnForm.InventoryComponent,
    //xnForm.WarehouseMovementCostComponent,
    //xnForm.EmailSettingComponent,
    xnForm.ModuleSearchDialogComponent,
    //xnForm.PurchaseFormCombineComponent,
    //xnForm.PurchaseFormHeaderComponent,
    //xnForm.PurchaseFormArticleComponent,
    //xnForm.HotKeySettingDialogComponent,
    xnForm.ChangePasswordFormComponent,
    xnForm.UserProfileFormComponent,
    //xnForm.FeedbackCombineComponent,
    //xnForm.FeedbackPopupComponent,
    //xnForm.FeedbackFormComponent,
    //xnForm.FeedbackImageReviewComponent,
    //xnForm.NotificationArchivePopupComponent,
    //xnForm.NotificationArchiveViewComponent,
    //xnForm.NotificationListViewChildComponent,
    //xnForm.NotificationListViewMainComponent,
    //xnForm.NotificationDetailPopupComponent,
    //xnForm.NotificationDetailComponent,
    //xnForm.XnFeedbackIconComponent,
    xnControl.XnCommunicationTableComponent,
    xnControl.XnCountryCheckListComponent,
    xnControl.CountryCheckListEditingComponent,
    xnControl.XnCreditCardComponent,
    xnControl.XnMessageModalComponent,
    xnControl.XnUsedCountryComponent,
    xnControl.XnNumbericTextboxComponent,
    xnControl.ScheduleSettingComponent,
    xnControl.ScheduleSettingFormComponent,
    xnControl.ScheduleSettingGridComponent,
    xnControl.ScheduleSettingRunImmediatelyComponent,
    xnControl.DateFilterComponent,
    xnControl.XnInputHorizontalComponent,
    xnControl.XnInputToggleComponent,

    xnControl.XnContextMenuComponent,
    xnControl.XnTreeViewComponent,
    xnControl.XnTreeViewLeftComponent,
    xnControl.XnTreeViewRightComponent,
    xnControl.XnFormStepProgessComponent,
    xnControl.ClearTextComponent,
    xnControl.SupportWijmoInputDateComponent,
    xnControl.ListBoxComponent,
    xnControl.CaptureLine,
    xnControl.CaptureItem,
    xnControl.CaptureItemList,
    xnControl.CircleProgressComponent,
    xnControl.SelCountryCheckListComponent,
    xnControl.XnCardContainerComponent,
    xnControl.XnDefaultCardComponent,
    xnControl.NoteControlComponent,

    //artMedia.ArticleImageGalleryComponent,
    //artMedia.ArticleGalleryFormComponent,
    //artMedia.ArticleMediaManagerComponent,
    //artMedia.ArticleDetailUploadComponent,
    //customerHistory.HistoryContainerComponent,
    //customerHistory.HistoryHeaderComponent,
    //customerHistory.HistoryBodyComponent,
    //customerHistory.HistoryFooterComponent,
    //customerHistory.HistoryDialogComponent,
    //customerHistory.HistoryListComponent,

    moduleWelcome.ModuleWelcomeComponent,
    moduleWelcome.ModuleWelcomeItemComponent,
    moduleWelcome.ModuleWelcomeSubModuleComponent,

    feedback.FeedbackFormComponent,
    feedback.FeedbackImageReviewComponent,
    feedback.FeedbackPopupComponent,
    feedback.XnFeedbackIconComponent,
    feedback.FeedbackCombineComponent,

    DialogApplyWidgetSettingsComponent,
    CapturedDocumentDetailComponent,
    WidgetContextMenuComponent,
    // WidgetScanningHistoryModule,
];
