export enum DatabaseControlTypeV2 {
    COMBOBOX = 'combobox',
    NVARCHAR = 'nvarchar',
    VARCHAR = 'varchar',
    TEXT = 'text',
    TEXT_AREA = 'textarea',
    DATE_TIME = 'datetime',
    DATE_TIME_PICKER = 'datetimepicker',
    DECIMAL = 'decimal',
    BIG_INT = 'bigint',
    INT = 'int',
    MONEY = 'money',
    BIT = 'bit',
    CHECKBOX = 'checkbox',
    AUTOCOMPLETE = 'autocomplete',
    IMAGE_SIGNATURE = 'signature',
    HTML_INPUT = 'html',
    SELECT_SEARCH = 'comboboxfilter',
    RADIO = 'radio',
}
